build_tables – TEMPO Microphysics
build_tables Program
20 statements
Source File
Uses
mpi_f08
module_mp_tempo_init
module_mp_tempo_params
program to build 3 lookup tables for tempo microphysics
example build make build_tables -f Makefile.intel mpi=1
timing information (ursa) to build the largest lookup table (rain-graupel collection)
Description Time (s)
gfortran (-O2) 3000
mpif90 (-O2) 1 process 3000
mpif90 (-O2) 13 processes 250
ifort (-fp-model consistent) 1300
mpiifort (-fp-model consistent) 1 process 1300
mpiifort (-fp-model consistent) 13 processes 120
Calls
Variables
Type Attributes Name Initial
integer :: build_tables_rank
integer :: build_tables_num_proc
integer :: ierror
integer :: mpi_dp_size
Call graph
build_tables calls mpi_comm_rank, mpi_comm_size, mpi_finalize, mpi_init, mpi_type_size, tempo_build_tables
tempo_build_tables calls mpi_allgather, mpi_barrier, mpi_gatherv, mpi_wtime, initialize_arrays_freezewater, initialize_arrays_qr_acr_qg, initialize_arrays_qr_acr_qs, initialize_bins_for_tables, initialize_graupel_vars, initialize_parameters, snow_moments
initialize_bins_for_tables calls create_bins