run_tempo_tests – TEMPO Microphysics
run_tempo_tests Program
20 statements
Source File
Uses
tests
runs tempo tests
Calls
Variables
Type Attributes Name Initial
real, dimension(7) :: sedi_tests = [1., 10., 20., 60., 120., 300., 600.]
integer :: t
Call graph
run_tempo_tests calls test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation, test_tempo_init
test_cloud_number_aerosolaware calls tempo_driver
test_cloud_number_ml calls tempo_driver
test_cloud_number_non_aerosolaware calls tempo_driver
test_graupel_sedimentation calls tempo_driver
test_ml_cloud_effective_radius calls tempo_driver
test_snow_sedimentation calls tempo_driver
test_tempo_init calls tempo_init
tempo_driver calls tempo_main
tempo_init calls compute_drop_evap, compute_efrw, compute_efsw, get_version, init_ml_data, initialize_array_efrw, initialize_array_efsw, initialize_arrays_ccn, initialize_arrays_drop_evap, initialize_arrays_freezewater, initialize_arrays_qi_aut_qs, initialize_arrays_qr_acr_qg, initialize_arrays_qr_acr_qs, initialize_bins_for_hail_size, initialize_bins_for_radar, initialize_bins_for_tables, initialize_graupel_vars, initialize_parameters, qi_aut_qs, read_table_ccn, read_table_freezewater, read_table_qr_acr_qg, read_table_qr_acr_qs
compute_drop_evap calls get_nuc
init_ml_data calls save_or_read_ml_data
initialize_bins_for_hail_size calls create_bins
initialize_bins_for_radar calls create_bins
initialize_bins_for_tables calls create_bins
qi_aut_qs calls calc_gamma_p
read_table_ccn calls check_before_table_read
read_table_freezewater calls check_before_table_read
read_table_qr_acr_qg calls check_before_table_read
read_table_qr_acr_qs calls check_before_table_read
tempo_main calls get_cloud_number, aerosol_check_and_update, aerosol_scavenging, check_over_depletion, cloud_check_and_update, cloud_condensation, cloud_fallspeed, effective_radius, freeze_cloud_melt_ice, freezing_rain, graupel_check_and_update, graupel_fallspeed, graupel_init, ice_check_and_update, ice_fallspeed, ice_nucleation, ice_processes, init_ice_friendly_aerosols, init_water_friendly_aerosols, max_hail_diam, melting, rain_check_and_update, rain_evaporation, rain_fallspeed, rain_snow_rain_graupel, reflectivity_10cm, riming, sedimentation, semilagrangian_sedimentation, snow_check_and_update, snow_fallspeed, snow_moments, sum_tendencies, thermo_vars, warm_rain
get_cloud_number calls get_constant_cloud_number, tempo_ml_predict_cloud_number
aerosol_scavenging calls aerosol_collection_efficiency
calc_gamma_p calls calc_gamma_cf, calc_gamma_series
cloud_check_and_update calls get_nuc
cloud_condensation calls activate_cloud_number, get_cloud_table_index
cloud_fallspeed calls get_nuc
effective_radius calls get_nuc, snow_moments
ice_nucleation calls demott_nucleation, get_cloud_table_index, get_in_table_index, get_rain_table_index, koop_nucleation
ice_processes calls get_ice_table_index, get_t1_subl
melting calls get_t1_subl
rain_snow_rain_graupel calls get_graupel_table_index, get_rain_table_index, get_snow_table_index, get_temperature_table_index
reflectivity_10cm calls find_melting_level, reflectivity_from_melting_graupel, reflectivity_from_melting_snow
riming calls get_nuc
thermo_vars calls calc_rsif, calc_rslf
warm_rain calls get_nuc
reflectivity_from_melting_graupel calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
reflectivity_from_melting_snow calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
tempo_ml_predict_cloud_number calls save_or_read_ml_data, relu_activation, standard_scaler_transform