aerosol_collection_efficiency – TEMPO Microphysics
aerosol_collection_efficiency Function
32 statements
Source File
public function aerosol_collection_efficiency(d, da, visc, rhoa, temp, species) result(eff_a)
Uses
module_mp_tempo_params
computes aerosol collection efficiency for precipitation scavenging from Wang et al. (2010)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: d
real(kind=wp), intent(in) :: da
real(kind=wp), intent(in) :: visc
real(kind=wp), intent(in) :: rhoa
real(kind=wp), intent(in) :: temp
character(len=1), intent(in) :: species
Return Value real(kind=wp)
Called by
Call graph
aerosol_scavenging calls aerosol_collection_efficiency
tempo_main calls aerosol_scavenging
tempo_driver calls tempo_main
test_graupel_sedimentation calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_graupel_sedimentation, test_snow_sedimentation