calc_rslf – TEMPO Microphysics
calc_rslf Function
18 statements
Source File
public function calc_rslf(p, t) result(rslf)
calculates liquid saturation vapor mixing ratio
Note
even with p = 1050 mb and t = 55 C, the saturation vapor pressure only contributes to 15% of the total pressure, thus the limit on the saturation vapor pressure is set to 15%
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: p
real(kind=wp), intent(in) :: t
Return Value real(kind=wp)
Called by
Call graph
thermo_vars calls calc_rslf
tempo_main calls thermo_vars
tempo_driver calls tempo_main
test_graupel_sedimentation calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_graupel_sedimentation, test_snow_sedimentation