check_before_table_read – TEMPO Microphysics
check_before_table_read Subroutine
30 statements
Source File
private subroutine check_before_table_read(filename, table_size)
checks that lookup tables exist and are the correct size before attempting to read them
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer, intent(in) :: table_size
Called by
Call graph
read_table_ccn calls check_before_table_read
read_table_freezewater calls check_before_table_read
read_table_qr_acr_qg calls check_before_table_read
read_table_qr_acr_qs calls check_before_table_read
tempo_init calls read_table_ccn, read_table_freezewater, read_table_qr_acr_qg, read_table_qr_acr_qs