get_nuc – TEMPO Microphysics
get_nuc Function
10 statements
Source File
public function get_nuc(nc) result(nu_c)
Uses
module_mp_tempo_params
returns nu_c for cloud water (values from 2-15)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: nc
Return Value integer
Called by
Call graph
cloud_check_and_update calls get_nuc
cloud_fallspeed calls get_nuc
compute_drop_evap calls get_nuc
effective_radius calls get_nuc
riming calls get_nuc
warm_rain calls get_nuc
tempo_init calls compute_drop_evap
tempo_main calls cloud_check_and_update, cloud_fallspeed, effective_radius, riming, warm_rain
tempo_driver calls tempo_main
test_tempo_init calls tempo_init
test_cloud_number_aerosolaware calls tempo_driver
test_cloud_number_ml calls tempo_driver
test_cloud_number_non_aerosolaware calls tempo_driver
test_graupel_sedimentation calls tempo_driver
test_ml_cloud_effective_radius calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_tempo_init, test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation