get_rain_table_index – TEMPO Microphysics
get_rain_table_index Subroutine
25 statements
Source File
public subroutine get_rain_table_index(rr, ilamr, idx_r, idx_r1)
Uses
module_mp_tempo_params
get rain table indices from rain mass and lambda
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: rr
real(kind=dp), intent(in) :: ilamr
integer, intent(out) :: idx_r
integer, intent(out) :: idx_r1
Called by
Call graph
getraintableindex_massindexcorrect calls get_rain_table_index
getraintableindex_n0expindexcorrectmvd calls get_rain_table_index
ice_nucleation calls get_rain_table_index
rain_snow_rain_graupel calls get_rain_table_index
tempo_main calls ice_nucleation, rain_snow_rain_graupel
tempo_driver calls tempo_main
test_graupel_sedimentation calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_graupel_sedimentation, test_snow_sedimentation