get_cloud_table_index – TEMPO Microphysics
get_cloud_table_index Subroutine
15 statements
Source File
public subroutine get_cloud_table_index(rc, nc, idx_c, idx_n)
Uses
module_mp_tempo_params
get cloud table index from mass and number
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: rc
real(kind=wp), intent(in) :: nc
integer, intent(out) :: idx_c
integer, intent(out) :: idx_n
Called by
Call graph
cloud_condensation calls get_cloud_table_index
ice_nucleation calls get_cloud_table_index
tempo_main calls cloud_condensation, ice_nucleation
tempo_driver calls tempo_main
test_graupel_sedimentation calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_graupel_sedimentation, test_snow_sedimentation