get_t1_subl – TEMPO Microphysics
get_t1_subl Subroutine
20 statements
Source File
private subroutine get_t1_subl(rho, temp, qvsi, tcond, diffu, ssati, t1_subl)
Uses
module_mp_tempo_params
calculations thermodynamic term used in depositional growth and melting
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: rho
real(kind=wp), intent(in), dimension(:) :: temp
real(kind=wp), intent(in), dimension(:) :: qvsi
real(kind=wp), intent(in), dimension(:) :: tcond
real(kind=wp), intent(in), dimension(:) :: diffu
real(kind=wp), intent(in), dimension(:) :: ssati
real(kind=wp), intent(out), dimension(:) :: t1_subl
Called by
Call graph
ice_processes calls get_t1_subl
melting calls get_t1_subl
tempo_main calls ice_processes, melting
tempo_driver calls tempo_main
test_cloud_number_aerosolaware calls tempo_driver
test_cloud_number_ml calls tempo_driver
test_cloud_number_non_aerosolaware calls tempo_driver
test_graupel_sedimentation calls tempo_driver
test_ml_cloud_effective_radius calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation