mp_tempo_main – TEMPO Microphysics
mp_tempo_main Subroutine
2000 statements
Source File
public subroutine mp_tempo_main(qv1d, qc1d, qi1d, qr1d, qs1d, qg1d, qb1d, ni1d, nr1d, nc1d, ng1d, nwfa1d, nifa1d, t1d, p1d, w1d, dzq, pptrain, pptsnow, pptgraul, pptice, ext_diag, prw_vcdc1, prw_vcde1, tpri_inu1, tpri_ide1_d, tpri_ide1_s, tprs_ide1, tprs_sde1_d, tprs_sde1_s, tprg_gde1_d, tprg_gde1_s, tpri_iha1, tpri_wfz1, tpri_rfz1, tprg_rfz1, tprs_scw1, tprg_scw1, tprg_rcs1, tprs_rcs1, tprr_rci1, tprg_rcg1, tprw_vcd1_c, tprw_vcd1_e, tprr_sml1, tprr_gml1, tprr_rcg1, tprr_rcs1, tprv_rev1, tten1, qvten1, qrten1, qsten1, qgten1, qiten1, niten1, nrten1, ncten1, qcten1, decfl, pfil1, pfll1, lsml, rand1, rand2, rand3, kts, kte, dt, ii, jj)
! #if defined(mpas) configs)
! Ef_rr = 1.0 - exp(2300.0*(mvd_r(k)-1950.0E-6)) - Rain collecting cloud water. In CE, assume Dc<
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(kts:kte) :: qv1d
real(kind=wp), intent(inout), dimension(kts:kte) :: qc1d
real(kind=wp), intent(inout), dimension(kts:kte) :: qi1d
real(kind=wp), intent(inout), dimension(kts:kte) :: qr1d
real(kind=wp), intent(inout), dimension(kts:kte) :: qs1d
real(kind=wp), intent(inout), dimension(kts:kte) :: qg1d
real(kind=wp), intent(inout), dimension(kts:kte) :: qb1d
real(kind=wp), intent(inout), dimension(kts:kte) :: ni1d
real(kind=wp), intent(inout), dimension(kts:kte) :: nr1d
real(kind=wp), intent(inout), dimension(kts:kte) :: nc1d
real(kind=wp), intent(inout), dimension(kts:kte) :: ng1d
real(kind=wp), intent(inout), dimension(kts:kte) :: nwfa1d
real(kind=wp), intent(inout), dimension(kts:kte) :: nifa1d
real(kind=wp), intent(inout), dimension(kts:kte) :: t1d
real(kind=wp), intent(in), dimension(kts:kte) :: p1d
real(kind=wp), intent(in), dimension(kts:kte) :: w1d
real(kind=wp), intent(in), dimension(kts:kte) :: dzq
real(kind=wp), intent(inout) :: pptrain
real(kind=wp), intent(inout) :: pptsnow
real(kind=wp), intent(inout) :: pptgraul
real(kind=wp), intent(inout) :: pptice
logical, intent(in) :: ext_diag
real(kind=wp), intent(out), optional, dimension(:) :: prw_vcdc1
real(kind=wp), intent(out), optional, dimension(:) :: prw_vcde1
real(kind=wp), intent(out), optional, dimension(:) :: tpri_inu1
real(kind=wp), intent(out), optional, dimension(:) :: tpri_ide1_d
real(kind=wp), intent(out), optional, dimension(:) :: tpri_ide1_s
real(kind=wp), intent(out), optional, dimension(:) :: tprs_ide1
real(kind=wp), intent(out), optional, dimension(:) :: tprs_sde1_d
real(kind=wp), intent(out), optional, dimension(:) :: tprs_sde1_s
real(kind=wp), intent(out), optional, dimension(:) :: tprg_gde1_d
real(kind=wp), intent(out), optional, dimension(:) :: tprg_gde1_s
real(kind=wp), intent(out), optional, dimension(:) :: tpri_iha1
real(kind=wp), intent(out), optional, dimension(:) :: tpri_wfz1
real(kind=wp), intent(out), optional, dimension(:) :: tpri_rfz1
real(kind=wp), intent(out), optional, dimension(:) :: tprg_rfz1
real(kind=wp), intent(out), optional, dimension(:) :: tprs_scw1
real(kind=wp), intent(out), optional, dimension(:) :: tprg_scw1
real(kind=wp), intent(out), optional, dimension(:) :: tprg_rcs1
real(kind=wp), intent(out), optional, dimension(:) :: tprs_rcs1
real(kind=wp), intent(out), optional, dimension(:) :: tprr_rci1
real(kind=wp), intent(out), optional, dimension(:) :: tprg_rcg1
real(kind=wp), intent(out), optional, dimension(:) :: tprw_vcd1_c
real(kind=wp), intent(out), optional, dimension(:) :: tprw_vcd1_e
real(kind=wp), intent(out), optional, dimension(:) :: tprr_sml1
real(kind=wp), intent(out), optional, dimension(:) :: tprr_gml1
real(kind=wp), intent(out), optional, dimension(:) :: tprr_rcg1
real(kind=wp), intent(out), optional, dimension(:) :: tprr_rcs1
real(kind=wp), intent(out), optional, dimension(:) :: tprv_rev1
real(kind=wp), intent(out), optional, dimension(:) :: tten1
real(kind=wp), intent(out), optional, dimension(:) :: qvten1
real(kind=wp), intent(out), optional, dimension(:) :: qrten1
real(kind=wp), intent(out), optional, dimension(:) :: qsten1
real(kind=wp), intent(out), optional, dimension(:) :: qgten1
real(kind=wp), intent(out), optional, dimension(:) :: qiten1
real(kind=wp), intent(out), optional, dimension(:) :: niten1
real(kind=wp), intent(out), optional, dimension(:) :: nrten1
real(kind=wp), intent(out), optional, dimension(:) :: ncten1
real(kind=wp), intent(out), optional, dimension(:) :: qcten1
integer, intent(in), optional :: decfl
real(kind=wp), intent(out), optional, dimension(kts:kte) :: pfil1
real(kind=wp), intent(out), optional, dimension(kts:kte) :: pfll1
integer, intent(in), optional :: lsml
real(kind=wp), intent(in), optional :: rand1
real(kind=wp), intent(in), optional :: rand2
real(kind=wp), intent(in), optional :: rand3
integer, intent(in) :: kts
integer, intent(in) :: kte
real(kind=wp), intent(in) :: dt
type(ty_tempo_cfg), intent(in) :: configs
integer, intent(in) :: ii
integer, intent(in) :: jj
Calls
Called by
Call graph
mp_tempo_main calls alog, alog10, float, calc_rsif, calc_rslf, sngl
tempo_driver calls mp_tempo_main