rain_snow_rain_graupel – TEMPO Microphysics
rain_snow_rain_graupel Subroutine
58 statements
Source File
private subroutine rain_snow_rain_graupel(temp, l_qr, rr, nr, ilamr, l_qs, rs, l_qg, rg, ng, ilamg, idx, tend)
Uses
module_mp_tempo_params
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: temp
logical, intent(in), dimension(:) :: l_qr
real(kind=wp), intent(in), dimension(:) :: rr
real(kind=wp), intent(in), dimension(:) :: nr
real(kind=dp), intent(in), dimension(:) :: ilamr
logical, intent(in), dimension(:) :: l_qs
real(kind=wp), intent(in), dimension(:) :: rs
logical, intent(in), dimension(:) :: l_qg
real(kind=wp), intent(in), dimension(:) :: rg
real(kind=wp), intent(in), dimension(:) :: ng
real(kind=dp), intent(in), dimension(:) :: ilamg
integer, intent(in), dimension(:) :: idx
type(ty_tend), intent(inout) :: tend
Calls
Called by
Call graph
rain_snow_rain_graupel calls get_graupel_table_index, get_rain_table_index, get_snow_table_index, get_temperature_table_index
tempo_main calls rain_snow_rain_graupel
tempo_driver calls tempo_main