save_or_read_ml_data – TEMPO Microphysics
save_or_read_ml_data Subroutine
13 statements
Source File
public subroutine save_or_read_ml_data(ml_data_in, ml_data_out)
initializes and saves or returns neural network information
Arguments
Type Intent Optional Attributes Name
type(ty_tempo_ml_data), intent(in), optional, dimension(1) :: ml_data_in
type(ty_tempo_ml_data), intent(out), optional, dimension(1) :: ml_data_out
Called by
Call graph
init_ml_data calls save_or_read_ml_data
tempo_ml_predict_cloud_number calls save_or_read_ml_data
get_cloud_number calls tempo_ml_predict_cloud_number
tempo_init calls init_ml_data
tempo_main calls get_cloud_number
test_tempo_init calls tempo_init
tempo_driver calls tempo_main
run_tempo_tests calls test_tempo_init, test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation
test_cloud_number_aerosolaware calls tempo_driver
test_cloud_number_ml calls tempo_driver
test_cloud_number_non_aerosolaware calls tempo_driver
test_graupel_sedimentation calls tempo_driver
test_ml_cloud_effective_radius calls tempo_driver
test_snow_sedimentation calls tempo_driver