tempo_build_tables – TEMPO Microphysics
tempo_build_tables Subroutine
30 statements
Source File
public subroutine tempo_build_tables(build_tables_rank, build_tables_num_proc)
Uses
module_mp_tempo_params
builds three lookup tables for tempo microphysics
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: build_tables_rank
integer, intent(in) :: build_tables_num_proc
Calls
Called by
Call graph
tempo_build_tables calls build_table_freezewater, build_table_qr_acr_qg, build_table_qr_acr_qs, get_version, initialize_bins_for_tables, initialize_graupel_vars, initialize_parameters, write_table_freezewater, write_table_qr_acr_qg, write_table_qr_acr_qs
build_table_freezewater calls freezewater, initialize_arrays_freezewater
build_table_qr_acr_qg calls mpi_allgather, mpi_barrier, mpi_wtime, gather, get_index_for_rank, initialize_arrays_qr_acr_qg, qr_acr_qg
build_table_qr_acr_qs calls mpi_allgather, mpi_barrier, mpi_wtime, gather, get_index_for_rank, initialize_arrays_qr_acr_qs, qr_acr_qs
initialize_bins_for_tables calls create_bins
write_table_freezewater calls rename_file_if_exists
write_table_qr_acr_qg calls rename_file_if_exists
write_table_qr_acr_qs calls rename_file_if_exists
gather calls mpi_gatherv
qr_acr_qs calls snow_moments
build_tables calls tempo_build_tables