tempo_init – TEMPO Microphysics
tempo_init Subroutine
60 statements
Source File
public subroutine tempo_init(aerosolaware_flag, hailaware_flag)
Uses
module_mp_tempo_params
initialize tempo microphysics
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: aerosolaware_flag
logical, intent(in), optional :: hailaware_flag
Calls
Called by
Call graph
tempo_init calls compute_drop_evap, compute_efrw, compute_efsw, get_version, initialize_array_efrw, initialize_array_efsw, initialize_arrays_ccn, initialize_arrays_drop_evap, initialize_arrays_freezewater, initialize_arrays_qi_aut_qs, initialize_arrays_qr_acr_qg, initialize_arrays_qr_acr_qs, initialize_bins_for_hail_size, initialize_bins_for_radar, initialize_bins_for_tables, initialize_graupel_vars, initialize_parameters, qi_aut_qs, read_table_ccn, read_table_freezewater, read_table_qr_acr_qg, read_table_qr_acr_qs
compute_drop_evap calls get_nuc
initialize_bins_for_hail_size calls create_bins
initialize_bins_for_radar calls create_bins
initialize_bins_for_tables calls create_bins
qi_aut_qs calls calc_gamma_p
read_table_ccn calls check_before_table_read
read_table_freezewater calls check_before_table_read
read_table_qr_acr_qg calls check_before_table_read
read_table_qr_acr_qs calls check_before_table_read
calc_gamma_p calls calc_gamma_cf, calc_gamma_series
test_tempo_init calls tempo_init
run_tempo_tests calls test_tempo_init