tempo_main – TEMPO Microphysics
tempo_main Subroutine
519 statements
Source File
public subroutine tempo_main(tempo_cfgs, qv1d, qc1d, qi1d, qr1d, qs1d, qg1d, qb1d, ni1d, nr1d, nc1d, ng1d, nwfa1d, nifa1d, t1d, p1d, w1d, dz1d, land1d, qcfrac1d, qifrac1d, qc_bl1d, qcfrac_bl1d, thten_bl1d, qvten_bl1d, qcten_bl1d, qiten_bl1d, thten_lwrad1d, thten_swrad1d, kts, kte, dt, ii, jj, tempo_main_diags)
tempo main
Arguments
Type Intent Optional Attributes Name
type(ty_tempo_cfgs), intent(in) :: tempo_cfgs
real(kind=wp), intent(inout), dimension(kts:kte) :: qv1d
1D water vapor mixing ratio
real(kind=wp), intent(inout), dimension(kts:kte) :: qc1d
1D cloud water mass mixing ratio
real(kind=wp), intent(inout), dimension(kts:kte) :: qi1d
1D cloud ice mass mixing ratio
real(kind=wp), intent(inout), dimension(kts:kte) :: qr1d
1D rain water mass mixing ratio
real(kind=wp), intent(inout), dimension(kts:kte) :: qs1d
1D snow mass mixing ratio
real(kind=wp), intent(inout), dimension(kts:kte) :: qg1d
1D graupel mass mixing ratio
real(kind=wp), intent(inout), optional, dimension(:) :: qb1d
1D graupel volume mixing ratio
real(kind=wp), intent(inout), dimension(kts:kte) :: ni1d
1D cloud ice number mixing ratio
real(kind=wp), intent(inout), dimension(kts:kte) :: nr1d
1D rain water number mixing ratio
real(kind=wp), intent(inout), optional, dimension(:) :: nc1d
1D cloud water number mixing ratio
real(kind=wp), intent(inout), optional, dimension(:) :: ng1d
1D graupel number mixing ratio
real(kind=wp), intent(inout), optional, dimension(:) :: nwfa1d
1D water-friendly aerosol number mixing ratio
real(kind=wp), intent(inout), optional, dimension(:) :: nifa1d
1D ice-friendly aerosol number mixing ratio
real(kind=wp), intent(inout), dimension(kts:kte) :: t1d
1D temperature
real(kind=wp), intent(in), dimension(kts:kte) :: p1d
1D pressure
real(kind=wp), intent(in), dimension(kts:kte) :: w1d
1D vertical velocity
real(kind=wp), intent(in), dimension(kts:kte) :: dz1d
1D vertical grid spacing
integer, intent(in), optional :: land1d
grid-point land type
real(kind=wp), intent(inout), optional, dimension(:) :: qcfrac1d
cloud fraction
real(kind=wp), intent(inout), optional, dimension(:) :: qifrac1d
cloud ice fraction
real(kind=wp), intent(in), optional, dimension(:) :: qc_bl1d
cloud water mixing ratio from boundary layer scheme
real(kind=wp), intent(in), optional, dimension(:) :: qcfrac_bl1d
cloud fraction from boundary layer scheme
real(kind=wp), intent(in), optional, dimension(:) :: thten_bl1d
potential temperature tendency from boundary layer scheme
real(kind=wp), intent(in), optional, dimension(:) :: qvten_bl1d
water vapor mixing ratio tendency from boundary layer scheme
real(kind=wp), intent(in), optional, dimension(:) :: qcten_bl1d
cloud water mixing ratio tendency from boundary layer scheme
real(kind=wp), intent(in), optional, dimension(:) :: qiten_bl1d
cloud ice mixing ratio from boundary layer scheme
real(kind=wp), intent(in), optional, dimension(:) :: thten_lwrad1d
potential temperature tendency from longwave radiation scheme
real(kind=wp), intent(in), optional, dimension(:) :: thten_swrad1d
potential temperature tendency from shortwave radiation scheme
integer, intent(in) :: kts
integer, intent(in) :: kte
real(kind=wp), intent(in) :: dt
integer, intent(in) :: ii
integer, intent(in) :: jj
type(ty_tempo_main_diags), intent(out) :: tempo_main_diags
Calls
Called by
Call graph
tempo_main calls get_cloud_number, aerosol_check_and_update, aerosol_scavenging, check_over_depletion, cloud_check_and_update, cloud_condensation, cloud_fallspeed, effective_radius, freeze_cloud_melt_ice, freezing_rain, graupel_check_and_update, graupel_fallspeed, graupel_init, ice_check_and_update, ice_fallspeed, ice_nucleation, ice_processes, init_ice_friendly_aerosols, init_water_friendly_aerosols, max_hail_diam, melting, rain_check_and_update, rain_evaporation, rain_fallspeed, rain_snow_rain_graupel, reflectivity_10cm, resolve_nc_value, riming, sedimentation, semilagrangian_sedimentation, snow_check_and_update, snow_fallspeed, snow_moments, sum_tendencies, thermo_vars, warm_rain
get_cloud_number calls get_constant_cloud_number, tempo_ml_predict_cloud_number
aerosol_scavenging calls aerosol_collection_efficiency
cloud_check_and_update calls get_nuc
cloud_condensation calls activate_cloud_number, get_cloud_table_index
cloud_fallspeed calls get_nuc
effective_radius calls snow_moments, get_nuc
ice_nucleation calls demott_nucleation, get_cloud_table_index, get_in_table_index, get_rain_table_index, koop_nucleation
ice_processes calls get_ice_table_index, get_t1_subl
melting calls get_t1_subl
rain_snow_rain_graupel calls get_graupel_table_index, get_rain_table_index, get_snow_table_index, get_temperature_table_index
reflectivity_10cm calls find_melting_level, reflectivity_from_melting_graupel, reflectivity_from_melting_snow
riming calls get_nuc
thermo_vars calls calc_rsif, calc_rslf
warm_rain calls get_nuc
reflectivity_from_melting_graupel calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
reflectivity_from_melting_snow calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
tempo_ml_predict_cloud_number calls relu_activation, save_or_read_ml_data, standard_scaler_transform
tempo_run calls tempo_main
test_cloud_number_aerosolaware calls tempo_run
test_cloud_number_ml calls tempo_run
test_cloud_number_non_aerosolaware calls tempo_run
test_graupel_sedimentation calls tempo_run
test_ml_cloud_effective_radius calls tempo_run
test_snow_sedimentation calls tempo_run
run_tempo_tests calls test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation