tempo_ml_predict_number – TEMPO Microphysics
tempo_ml_predict_number Subroutine
74 statements
Source File
public subroutine tempo_ml_predict_number(qc, qr, qi, qs, pres, temp, w, predicted_number, predict_for_cloud)
predicts number concentration
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: qc
real(kind=wp), intent(in), dimension(:) :: qr
real(kind=wp), intent(in), dimension(:) :: qi
real(kind=wp), intent(in), dimension(:) :: qs
real(kind=wp), intent(in), dimension(:) :: pres
real(kind=wp), intent(in), dimension(:) :: temp
real(kind=wp), intent(in), dimension(:) :: w
real(kind=wp), intent(inout), dimension(:) :: predicted_number
logical, intent(in), optional :: predict_for_cloud
Calls
Call graph
tempo_ml_predict_number calls relu_activation, standard_scaler_transform, tempo_save_or_read_ml_data