tempo_3d_to_1d_driver – TEMPO Microphysics
tempo_3d_to_1d_driver Subroutine
284 statements
Source File
public subroutine tempo_3d_to_1d_driver(qv, qc, qr, qi, qs, qg, qb, ni, nr, nc, ng, nwfa, nifa, nwfa2d, nifa2d, th, pii, p, w, dz, dt_in, itimestep, rainnc, rainncv, snownc, snowncv, graupelnc, graupelncv, sr, frainnc, refl_10cm, diagflag, do_radar_ref, re_cloud, re_ice, re_snow, qcbl, cldfrac, has_reqc, has_reqi, has_reqs, ntc, muc, rainprod, evapprod, max_hail_diameter_column, max_hail_diameter_sfc, ids, ide, jds, jde, kds, kde, ims, ime, jms, jme, kms, kme, its, ite, jts, jte, kts, kte)
! K LOOP enddo
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qv
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qc
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qr
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qi
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qs
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qg
real, intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: qb
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: ni
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: nr
real, intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: nc
real, intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: ng
real, intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: nwfa
real, intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: nifa
real, intent(in), optional, dimension(ims:ime, jms:jme) :: nwfa2d
real, intent(in), optional, dimension(ims:ime, jms:jme) :: nifa2d
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: th
real, intent(in), dimension(ims:ime, kms:kme, jms:jme) :: pii
real, intent(in), dimension(ims:ime, kms:kme, jms:jme) :: p
real, intent(in), dimension(ims:ime, kms:kme, jms:jme) :: w
real, intent(in), dimension(ims:ime, kms:kme, jms:jme) :: dz
real, intent(in) :: dt_in
integer, intent(in) :: itimestep
real, intent(inout), dimension(ims:ime, jms:jme) :: rainnc
real, intent(inout), dimension(ims:ime, jms:jme) :: rainncv
real, intent(inout), optional, dimension(ims:ime, jms:jme) :: snownc
real, intent(inout), optional, dimension(ims:ime, jms:jme) :: snowncv
real, intent(inout), optional, dimension(ims:ime, jms:jme) :: graupelnc
real, intent(inout), optional, dimension(ims:ime, jms:jme) :: graupelncv
real, intent(inout), dimension(ims:ime, jms:jme) :: sr
real, intent(inout), optional, dimension(ims:ime,jms:jme) :: frainnc
real, intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: refl_10cm
logical, intent(in), optional :: diagflag
integer, intent(in), optional :: do_radar_ref
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: re_cloud
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: re_ice
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: re_snow
real, intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: qcbl
real, intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: cldfrac
integer, intent(in) :: has_reqc
integer, intent(in) :: has_reqi
integer, intent(in) :: has_reqs
real, intent(in), optional, dimension(ims:ime, jms:jme) :: ntc
real, intent(in), optional, dimension(ims:ime, jms:jme) :: muc
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: rainprod
real, intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: evapprod
real, intent(inout), optional, dimension(ims:ime,jms:jme) :: max_hail_diameter_column
real, intent(inout), optional, dimension(ims:ime,jms:jme) :: max_hail_diameter_sfc
integer, intent(in) :: ids
integer, intent(in) :: ide
integer, intent(in) :: jds
integer, intent(in) :: jde
integer, intent(in) :: kds
integer, intent(in) :: kde
integer, intent(in) :: ims
integer, intent(in) :: ime
integer, intent(in) :: jms
integer, intent(in) :: jme
integer, intent(in) :: kms
integer, intent(in) :: kme
integer, intent(in) :: its
integer, intent(in) :: ite
integer, intent(in) :: jts
integer, intent(in) :: jte
integer, intent(in) :: kts
integer, intent(in) :: kte
Calls
Call graph
tempo_3d_to_1d_driver calls calc_effectrad, calc_refl10cm, hail_size_diagnostics, mp_tempo_main, predict_number_sub
calc_effectrad calls sngl
calc_refl10cm calls dexp, rayleigh_soak_wetgraupel, sngl
hail_size_diagnostics calls create_bins
mp_tempo_main calls alog, alog10, float, calc_rsif, calc_rslf, sngl
predict_number_sub calls tempo_save_or_read_ml_data