tempo_ml_predict_cloud_number – TEMPO Microphysics
tempo_ml_predict_cloud_number Subroutine
65 statements
Source File
public subroutine tempo_ml_predict_cloud_number(qc, qr, qi, qs, pres, temp, w, predicted_number)
predicts number concentration
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: qc
real(kind=wp), intent(in), dimension(:) :: qr
real(kind=wp), intent(in), dimension(:) :: qi
real(kind=wp), intent(in), dimension(:) :: qs
real(kind=wp), intent(in), dimension(:) :: pres
real(kind=wp), intent(in), dimension(:) :: temp
real(kind=wp), intent(in), dimension(:) :: w
real(kind=wp), intent(inout), dimension(:) :: predicted_number
Calls
Called by
Call graph
tempo_ml_predict_cloud_number calls relu_activation, save_or_read_ml_data, standard_scaler_transform
get_cloud_number calls tempo_ml_predict_cloud_number
tempo_main calls get_cloud_number
tempo_driver calls tempo_main
test_graupel_sedimentation calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_graupel_sedimentation, test_snow_sedimentation