tempo_run – TEMPO Microphysics
tempo_run Subroutine
253 statements
Source File
public subroutine tempo_run(tempo_cfgs, dt, itimestep, t, th, pii, p, w, dz, qv, qc, qr, qi, qs, qg, ni, nr, nc, nwfa, nifa, ng, qb, qc_bl, qcfrac_bl, qcfrac, qifrac, thten_bl, qvten_bl, qcten_bl, qiten_bl, thten_lwrad, thten_swrad, land_input, ids, ide, jds, jde, kds, kde, ims, ime, jms, jme, kms, kme, its, ite, jts, jte, kts, kte, tempo_diags)
\section arg_table_tempo_run Argument Table \htmlinclude tempo_run.html
Arguments
Type Intent Optional Attributes Name
type(ty_tempo_cfgs), intent(in) :: tempo_cfgs
real(kind=wp), intent(in) :: dt
timestep
integer, intent(in) :: itimestep
integer timestep = integration time / dt
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: t
temperature
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: th
theta
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: pii
exner function
real(kind=wp), intent(in), dimension(ims:ime, kms:kme, jms:jme) :: p
pressure
real(kind=wp), intent(in), dimension(ims:ime, kms:kme, jms:jme) :: w
vertical velocity
real(kind=wp), intent(in), dimension(ims:ime, kms:kme, jms:jme) :: dz
vertical grid spacing
real(kind=wp), intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qv
3D water vapor mixing ratio
real(kind=wp), intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qc
3D cloud water mass mixing ratio
real(kind=wp), intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qr
3D rain water mass mixing ratio
real(kind=wp), intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qi
3D cloud ice mass mixing ratio
real(kind=wp), intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qs
3D snow mass mixing ratio
real(kind=wp), intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: qg
3D graupel mass mixing ratio
real(kind=wp), intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: ni
3D cloud ice number mixing ratio
real(kind=wp), intent(inout), dimension(ims:ime, kms:kme, jms:jme) :: nr
3D rain water number mixing ratio
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: nc
3D cloud water number mixing ratio (aerosol-aware)
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: nwfa
3D water-friendly aerosol number mixing ratio (aerosol-aware)
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: nifa
3D ice-friendly aerosol number mixing ratio (aerosol-aware)
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: ng
3D graupel number mixing ratio (hail-aware)
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: qb
3D graupel volume mixing ratio (hail-aware)
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: qc_bl
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: qcfrac_bl
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: qcfrac
real(kind=wp), intent(inout), optional, dimension(ims:ime, kms:kme, jms:jme) :: qifrac
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: thten_bl
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: qvten_bl
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: qcten_bl
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: qiten_bl
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: thten_lwrad
real(kind=wp), intent(in), optional, dimension(ims:ime, kms:kme, jms:jme) :: thten_swrad
integer, intent(in), optional, dimension(ims:ime, jms:jme) :: land_input
land input value to differentiate land from ocean
integer, intent(in) :: ids
domain locations
integer, intent(in) :: ide
domain locations
integer, intent(in) :: jds
domain locations
integer, intent(in) :: jde
domain locations
integer, intent(in) :: kds
domain locations
integer, intent(in) :: kde
domain locations
integer, intent(in) :: ims
memory locations
integer, intent(in) :: ime
memory locations
integer, intent(in) :: jms
memory locations
integer, intent(in) :: jme
memory locations
integer, intent(in) :: kms
memory locations
integer, intent(in) :: kme
memory locations
integer, intent(in) :: its
tile locations
integer, intent(in) :: ite
tile locations
integer, intent(in) :: jts
tile locations
integer, intent(in) :: jte
tile locations
integer, intent(in) :: kts
tile locations
integer, intent(in) :: kte
tile locations
type(ty_tempo_driver_diags), intent(inout) :: tempo_diags
Calls
Called by
Call graph
tempo_run calls tempo_main
tempo_main calls get_cloud_number, aerosol_check_and_update, aerosol_scavenging, check_over_depletion, cloud_check_and_update, cloud_condensation, cloud_fallspeed, effective_radius, freeze_cloud_melt_ice, freezing_rain, graupel_check_and_update, graupel_fallspeed, graupel_init, ice_check_and_update, ice_fallspeed, ice_nucleation, ice_processes, init_ice_friendly_aerosols, init_water_friendly_aerosols, max_hail_diam, melting, rain_check_and_update, rain_evaporation, rain_fallspeed, rain_snow_rain_graupel, reflectivity_10cm, resolve_nc_value, riming, sedimentation, semilagrangian_sedimentation, snow_check_and_update, snow_fallspeed, snow_moments, sum_tendencies, thermo_vars, warm_rain
get_cloud_number calls get_constant_cloud_number, tempo_ml_predict_cloud_number
aerosol_scavenging calls aerosol_collection_efficiency
cloud_check_and_update calls get_nuc
cloud_condensation calls activate_cloud_number, get_cloud_table_index
cloud_fallspeed calls get_nuc
effective_radius calls snow_moments, get_nuc
ice_nucleation calls demott_nucleation, get_cloud_table_index, get_in_table_index, get_rain_table_index, koop_nucleation
ice_processes calls get_ice_table_index, get_t1_subl
melting calls get_t1_subl
rain_snow_rain_graupel calls get_graupel_table_index, get_rain_table_index, get_snow_table_index, get_temperature_table_index
reflectivity_10cm calls find_melting_level, reflectivity_from_melting_graupel, reflectivity_from_melting_snow
riming calls get_nuc
thermo_vars calls calc_rsif, calc_rslf
warm_rain calls get_nuc
reflectivity_from_melting_graupel calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
reflectivity_from_melting_snow calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
tempo_ml_predict_cloud_number calls relu_activation, save_or_read_ml_data, standard_scaler_transform
test_cloud_number_aerosolaware calls tempo_run
test_cloud_number_ml calls tempo_run
test_cloud_number_non_aerosolaware calls tempo_run
test_graupel_sedimentation calls tempo_run
test_ml_cloud_effective_radius calls tempo_run
test_snow_sedimentation calls tempo_run
run_tempo_tests calls test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation