test_graupel_sedimentation – TEMPO Microphysics
test_graupel_sedimentation Subroutine
78 statements
Source File
public subroutine test_graupel_sedimentation(dt, semi_sedi)
Uses
module_mp_tempo_params
test graupel sedimentation
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dt
logical, intent(in) :: semi_sedi
Calls
Called by
Call graph
test_graupel_sedimentation calls tempo_run
tempo_run calls tempo_main
tempo_main calls get_cloud_number, aerosol_check_and_update, aerosol_scavenging, check_over_depletion, cloud_check_and_update, cloud_condensation, cloud_fallspeed, effective_radius, freeze_cloud_melt_ice, freezing_rain, graupel_check_and_update, graupel_fallspeed, graupel_init, ice_check_and_update, ice_fallspeed, ice_nucleation, ice_processes, init_ice_friendly_aerosols, init_water_friendly_aerosols, max_hail_diam, melting, rain_check_and_update, rain_evaporation, rain_fallspeed, rain_snow_rain_graupel, reflectivity_10cm, resolve_nc_value, riming, sedimentation, semilagrangian_sedimentation, snow_check_and_update, snow_fallspeed, snow_moments, sum_tendencies, thermo_vars, warm_rain
get_cloud_number calls get_constant_cloud_number, tempo_ml_predict_cloud_number
aerosol_scavenging calls aerosol_collection_efficiency
cloud_check_and_update calls get_nuc
cloud_condensation calls activate_cloud_number, get_cloud_table_index
cloud_fallspeed calls get_nuc
effective_radius calls snow_moments, get_nuc
ice_nucleation calls demott_nucleation, get_cloud_table_index, get_in_table_index, get_rain_table_index, koop_nucleation
ice_processes calls get_ice_table_index, get_t1_subl
melting calls get_t1_subl
rain_snow_rain_graupel calls get_graupel_table_index, get_rain_table_index, get_snow_table_index, get_temperature_table_index
reflectivity_10cm calls find_melting_level, reflectivity_from_melting_graupel, reflectivity_from_melting_snow
riming calls get_nuc
thermo_vars calls calc_rsif, calc_rslf
warm_rain calls get_nuc
reflectivity_from_melting_graupel calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
reflectivity_from_melting_snow calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
tempo_ml_predict_cloud_number calls relu_activation, save_or_read_ml_data, standard_scaler_transform
run_tempo_tests calls test_graupel_sedimentation