warm_rain – TEMPO Microphysics
warm_rain Subroutine
49 statements
Source File
private subroutine warm_rain(rhof, l_qc, rc, nc, ilamc, mvd_c, l_qr, rr, nr, mvd_r, tend)
Uses
module_mp_tempo_params
computes warm-rain process rates -- condensation/evaporation happen later
Note
rain self-collection is from Seifert and Beheng (2001) and drop break-up follows Verlinde and Cotton (1993)
autoconversion follows Berry and Reinhardt (1974) with characteristic diameters correctly computed from gamma distribution of cloud droplets
rain collecting cloud water - assumes dc << dr and vtc
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: rhof
logical, intent(in), dimension(:) :: l_qc
real(kind=wp), intent(in), dimension(:) :: rc
real(kind=wp), intent(in), dimension(:) :: nc
real(kind=dp), intent(in), dimension(:) :: ilamc
real(kind=wp), intent(in), dimension(:) :: mvd_c
logical, intent(in), dimension(:) :: l_qr
real(kind=wp), intent(in), dimension(:) :: rr
real(kind=wp), intent(in), dimension(:) :: nr
real(kind=wp), intent(in), dimension(:) :: mvd_r
type(ty_tend), intent(inout) :: tend
Calls
Called by
Call graph
warm_rain calls get_nuc
tempo_main calls warm_rain
tempo_driver calls tempo_main
test_graupel_sedimentation calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_graupel_sedimentation, test_snow_sedimentation