get_cloud_number – TEMPO Microphysics
get_cloud_number Interface
4 statements
Source File
private interface get_cloud_number
Calls
Called by
Module Procedures
public subroutine tempo_ml_predict_cloud_number(qc, qr, qi, qs, pres, temp, w, predicted_number)
predicts number concentration
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: qc
real(kind=wp), intent(in), dimension(:) :: qr
real(kind=wp), intent(in), dimension(:) :: qi
real(kind=wp), intent(in), dimension(:) :: qs
real(kind=wp), intent(in), dimension(:) :: pres
real(kind=wp), intent(in), dimension(:) :: temp
real(kind=wp), intent(in), dimension(:) :: w
real(kind=wp), intent(inout), dimension(:) :: predicted_number
public subroutine get_constant_cloud_number(land, nc)
returns land-specific value of cloud droplet number concentration when aerosol-aware = false if land = 1, else returns ocean-specific value
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: land
real(kind=wp), intent(out), dimension(:) :: nc
Call graph
get_cloud_number calls get_constant_cloud_number, tempo_ml_predict_cloud_number
tempo_ml_predict_cloud_number calls relu_activation, save_or_read_ml_data, standard_scaler_transform
tempo_main calls get_cloud_number
tempo_driver calls tempo_main
test_graupel_sedimentation calls tempo_driver
test_snow_sedimentation calls tempo_driver
run_tempo_tests calls test_graupel_sedimentation, test_snow_sedimentation